import { default as AF } from "./flags/afghanistan.react.svg";
import { default as AX } from "./flags/alandIslands.react.svg";
import { default as AL } from "./flags/albania.react.svg";

export const options = [
  {
    name: "Afghanistan (‫افغانستان‬‎)",
    dialCode: "+93",
    code: "AF",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Åland Islands (Ahvenanmaa)",
    dialCode: "+358",
    code: "AX",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Albania (Shqipëria)",
    dialCode: "+355",
    code: "AL",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Afghanistan (‫افغانستان‬‎)",
    dialCode: "+93",
    code: "AF",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Åland Islands (Ahvenanmaa)",
    dialCode: "+358",
    code: "AX",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Albania (Shqipëria)",
    dialCode: "+355",
    code: "AL",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Afghanistan (‫افغانستان‬‎)",
    dialCode: "+93",
    code: "AF",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Åland Islands (Ahvenanmaa)",
    dialCode: "+358",
    code: "AX",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Albania (Shqipëria)",
    dialCode: "+355",
    code: "AL",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Afghanistan (‫افغانستان‬‎)",
    dialCode: "+93",
    code: "AF",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Åland Islands (Ahvenanmaa)",
    dialCode: "+358",
    code: "AX",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Albania (Shqipëria)",
    dialCode: "+355",
    code: "AL",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Afghanistan (‫افغانستان‬‎)",
    dialCode: "+93",
    code: "AF",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Åland Islands (Ahvenanmaa)",
    dialCode: "+358",
    code: "AX",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Albania (Shqipëria)",
    dialCode: "+355",
    code: "AL",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Afghanistan (‫افغانستان‬‎)",
    dialCode: "+93",
    code: "AF",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Åland Islands (Ahvenanmaa)",
    dialCode: "+358",
    code: "AX",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
  {
    name: "Albania (Shqipëria)",
    dialCode: "+355",
    code: "AL",
    mask: null,
    flag: "./flags/albania.react.svg",
  },
];
