import i18next from "i18next";

import { translations } from "SRC_DIR/autoGeneratedTranslations";

const fallbackLng = "en";

const resources: {
  [key: string]: { [key: string]: {} };
} = {};

translations.forEach((lngCol: Map<string, {}>, key: string) => {
  resources[key] = {};
  lngCol.forEach((data, ns: string) => {
    if (resources[key]) {
      resources[key][ns] = data;
    }
  });
});

i18next.init({
  fallbackLng: fallbackLng,
  load: "currentOnly",

  saveMissing: true,
  ns: ["Login", "Errors", "Common"],
  defaultNS: "Login",

  resources,

  interpolation: {
    escapeValue: false,
    format: function (value, format) {
      if (format === "lowercase") return value.toLowerCase();
      return value;
    },
  },
});

export default i18next;
