export const mockData = [
  {
    id: 0,
    displayName: "Lydia Calzoni",
    role: "Сотрудник",
    startFillingStatus: "Start filling",
    startFillingDate: "15.01.2023 17:56",
    filledAndSignedStatus: "Filled and signed",
    filledAndSignedDate: "26.01.2023 13:56",
    returnedByUser: "Returned by Teacher",
    returnedByUserDate: "25.01.2023 13:56",
    comment: "The registration block is filled in incorrectly. It is necessary to specify the user ID, and the email is specified. The user ID can be viewed on the profile page.",
    avatar: null,
  },
  {
    id: 1,
    displayName: "Dulce Vaccaro",
    role: "Бухгалтер",
    startFillingStatus: "Start filling",
    startFillingDate: "21.01.2023 17:56",
    filledAndSignedStatus: "Filled and signed",
    filledAndSignedDate: "23.01.2023 14:56",
    returnedByUser: "Returned by Teacher",
    returnedByUserDate: "22.01.2023 13:56",
    comment: null,
    avatar: null,
  },
  {
    id: 2,
    displayName: "Kaiya Franci",
    role: "Директор",
    startFillingStatus: "Start filling",
    startFillingDate: "12.01.2023 16:31",
    filledAndSignedStatus: "Filled and signed",
    filledAndSignedDate: "18.01.2023 11:56",
    returnedByUser: null,
    returnedByUserDate: null,
    comment: null,
    avatar: null,
  },
];
