/**
 * Array for generation current settings tree.
 */

export const settingsTree = [
  {
    id: "portal-settings_catalog-common",
    key: "0",
    icon: "/static/images/common-settings.svg",
    link: "common",
    tKey: "Common:Common",
    isHeader: true,
    children: [
      {
        id: "portal-settings_catalog-customization",
        key: "0-0",
        icon: "",
        link: "customization",
        tKey: "Customization",
        isCategory: true,
        children: [
          {
            id: "portal-settings_catalog-language-and-time-zone",
            key: "0-0-0",
            icon: "",
            link: "language-and-time-zone",
            tKey: "StudioTimeLanguageSettings",
          },
          {
            id: "portal-settings_catalog-welcome-page-settings",
            key: "0-0-1",
            icon: "",
            link: "welcome-page-settings",
            tKey: "CustomTitlesWelcome",
          },
          {
            id: "portal-settings_catalog-dns-settings",
            key: "0-0-2",
            icon: "",
            link: "dns-settings",
            tKey: "DNSSettings",
          },
          {
            id: "portal-settings_catalog-portal-renaming",
            key: "0-0-3",
            icon: "",
            link: "portal-renaming",
            tKey: "PortalRenaming",
          },
        ],
      },
      {
        id: "portal-settings_catalog-branding",
        key: "0-1",
        icon: "",
        link: "branding",
        tKey: "Branding",
        isCategory: true,
        children: [
          {
            id: "portal-settings_catalog-white-label",
            key: "0-1-0",
            icon: "",
            link: "white-label",
            tKey: "WhiteLabel",
          },
          {
            id: "portal-settings_catalog-company-info-settings",
            key: "0-1-1",
            icon: "",
            link: "company-info-settings",
            tKey: "CompanyInfoSettings",
          },
          {
            id: "portal-settings_catalog-additional-resources",
            key: "0-1-2",
            icon: "",
            link: "additional-resources",
            tKey: "AdditionalResources",
          },
        ],
      },
      {
        id: "portal-settings_catalog-appearance",
        key: "0-2",
        icon: "",
        link: "appearance",
        tKey: "Appearance",
        isCategory: true,
        children: [
          {
            id: "portal-settings_catalog-appearance_subLink",
            key: "0-2-0",
            icon: "",
            link: "appearance",
            tKey: "Appearance",
          },
        ],
      },
    ],
  },
  {
    id: "portal-settings_catalog-security",
    key: "1",
    icon: "/images/security-settings.svg",
    link: "security",
    tKey: "ManagementCategorySecurity",
    isHeader: true,
    children: [
      {
        id: "portal-settings_catalog-access-portal",
        key: "1-0",
        icon: "",
        link: "access-portal",
        tKey: "PortalAccess",
        isCategory: true,
        children: [
          {
            id: "portal-settings_catalog-password",
            key: "1-0-0",
            icon: "",
            link: "password",
            tKey: "SettingPasswordStrength",
          },
          {
            id: "portal-settings_catalog-two-factor-auth",
            key: "1-0-1",
            icon: "",
            link: "tfa",
            tKey: "TwoFactorAuth",
          },
          {
            id: "portal-settings_catalog-trusted-mail",
            key: "1-0-2",
            icon: "",
            link: "trusted-mail",
            tKey: "TrustedMail",
          },
          {
            id: "portal-settings_catalog-ip-security",
            key: "1-0-3",
            icon: "",
            link: "ip",
            tKey: "IPSecurity",
          },
          {
            id: "portal-settings_catalog-admin-message",
            key: "1-0-4",
            icon: "",
            link: "admin-message",
            tKey: "AdminsMessage",
          },
          {
            id: "portal-settings_catalog-session-life-time",
            key: "1-0-5",
            icon: "",
            link: "lifetime",
            tKey: "SessionLifetime",
          },
        ],
      },
      {
        id: "portal-settings_catalog-access-rights",
        key: "1-1",
        icon: "",
        link: "access-rights",
        tKey: "AccessRights",
        isCategory: true,
        children: [
          {
            key: "1-1-0",
            icon: "",
            link: "admins",
            tKey: "Admins",
          },
        ],
      },
      {
        id: "portal-settings_catalog-login-history",
        key: "1-2",
        icon: "",
        link: "login-history",
        tKey: "LoginHistoryTitle",
        isCategory: true,
      },
      {
        id: "portal-settings_catalog-audit-trail",
        key: "1-3",
        icon: "",
        link: "audit-trail",
        tKey: "AuditTrailNav",
        isCategory: true,
      },
    ],
  },
  {
    id: "portal-settings_catalog-integration",
    key: "3",
    icon: "/images/integration-settings.svg",
    link: "integration",
    tKey: "ManagementCategoryIntegration",
    isHeader: true,
    children: [
      {
        id: "portal-settings_catalog-single-sign-on",
        key: "3-0",
        icon: "",
        link: "single-sign-on",
        tKey: "SingleSignOn",
        isCategory: true,
      },
      {
        id: "portal-settings_catalog-third-party-services",
        key: "3-1",
        icon: "",
        link: "third-party-services",
        tKey: "ThirdPartyAuthorization",
        isCategory: true,
      },
      {
        id: "portal-settings_catalog-portal-integration",
        key: "3-2",
        icon: "",
        link: "portal-integration",
        tKey: "PortalIntegration",
        isCategory: true,
      },
      {
        id: "portal-settings_catalog-plugins",
        key: "3-3",
        icon: "",
        link: "plugins",
        tKey: "Plugins",
        isCategory: true,
      },
    ],
  },
  {
    id: "portal-settings_catalog-payments",
    key: "4",
    icon: "/images/payment.react.svg",
    link: "payments",
    tKey: "Payments",
    isHeader: true,
    children: [
      {
        id: "portal-settings_catalog-portal-payments",
        key: "4-0",
        icon: "",
        link: "portal-payments",
        tKey: "Payments",
        isCategory: true,
      },
    ],
  },
  {
    id: "portal-settings_catalog-backup",
    key: "5",
    icon: "/images/data-management.react.svg",
    link: "backup",
    tKey: "Backup",
    isHeader: true,
    children: [
      {
        id: "portal-settings_catalog-data-backup",
        key: "5-0",
        icon: "",
        link: "data-backup",
        tKey: "Backup",
        isCategory: true,
      },
      {
        id: "portal-settings_catalog-auto-backup",
        key: "5-1",
        icon: "",
        link: "auto-backup",
        tKey: "AutoBackup",
        isCategory: true,
      },
    ],
  },

  {
    id: "portal-settings_catalog-restore",
    key: "6",
    icon: "/images/restore.react.svg",
    link: "restore",
    tKey: "RestoreBackup",
    isHeader: true,
    children: [
      {
        key: "6-0",
        icon: "",
        link: "restore-backup",
        tKey: "RestoreBackup",
        isCategory: true,
      },
    ],
  },
  {
    id: "portal-settings_catalog-delete",
    key: "7",
    icon: "/images/trash.react.svg",
    link: "delete-data",
    tKey: "PortalDeletion",
    isHeader: true,
    children: [
      {
        key: "7-0",
        icon: "",
        link: "deletion",
        tKey: "PortalDeletion",
        isCategory: true,
      },
      {
        key: "7-1",
        icon: "",
        link: "deactivation",
        tKey: "PortalDeactivation",
        isCategory: true,
      },
    ],
  },
];

/**
* Array for generation full settings tree, old structure.
param title is unused
param link also used as translation key
*/
export const settingsTreeFull = [
  {
    title: "Common",
    key: "0",
    icon: "/static/images/settings.react.svg",
    link: "common",
    children: [
      {
        title: "Customization",
        key: "0-0",
        icon: "",
        link: "customization",
      },
      {
        title: "Modules & tools",
        key: "0-1",
        icon: "",
        link: "modules-and-tools",
      },
      {
        title: "White label",
        key: "0-2",
        icon: "",
        link: "white-label",
      },
    ],
  },
  {
    title: "Security",
    key: "1",
    icon: "/static/images/settings.react.svg",
    link: "security",
    children: [
      {
        title: "Portal Access",
        key: "1-0",
        icon: "",
        link: "portal-access",
      },
      {
        title: "Access Rights",
        key: "1-1",
        icon: "",
        link: "access-rights",
      },
      {
        title: "Login History",
        key: "1-2",
        icon: "",
        link: "login-history",
      },
      {
        title: "Audit Trail",
        key: "1-3",
        icon: "",
        link: "audit-trail",
      },
    ],
  },
  {
    title: "Data Management",
    key: "2",
    icon: "/static/images/settings.react.svg",
    link: "data-management",
    children: [
      {
        title: "Migration",
        key: "2-0",
        icon: "",
        link: "migration",
      },
      {
        title: "Backup",
        key: "2-1",
        icon: "",
        link: "backup",
      },
      {
        title: "Portal Deactivation/Deletion",
        key: "2-2",
        icon: "",
        link: "portal-deactivation-deletion",
      },
    ],
  },
  {
    title: "Integration",
    key: "3",
    icon: "/static/images/settings.react.svg",
    link: "integration",
    children: [
      {
        title: "Third-Party Services",
        key: "3-0",
        icon: "",
        link: "third-party-services",
      },
      {
        key: "3-1",
        icon: "",
        link: "plugins",
        tKey: "Plugins",
      },
      {
        title: "SMTP Settings",
        key: "3-1",
        icon: "",
        link: "smtp-settings",
      },
    ],
  },
  {
    title: "Statistics",
    key: "4",
    icon: "/static/images/settings.react.svg",
    link: "statistics",
  },
];
