export const filesColumns = [
  {
    key: "Name",
    title: t("Common:Name"),
    resizable: true,
    enable: this.props.nameColumnIsEnabled,
    default: true,
    sortBy: "AZ",
    minWidth: 210,
    onClick: this.onFilter,
  },
  {
    key: "Author",
    title: t("ByAuthor"),
    enable: this.props.authorColumnIsEnabled,
    resizable: true,
    sortBy: "Author",
    onClick: this.onFilter,
    onChange: this.onColumnChange,
  },
  {
    key: "Created",
    title: t("ByCreation"),
    enable: this.props.createdColumnIsEnabled,
    resizable: true,
    sortBy: "DateAndTimeCreation",
    onClick: this.onFilter,
    onChange: this.onColumnChange,
  },
  {
    key: "Modified",
    title: t("ByLastModified"),
    enable: this.props.modifiedColumnIsEnabled,
    resizable: true,
    sortBy: "DateAndTime",
    onClick: this.onFilter,
    onChange: this.onColumnChange,
  },
  {
    key: "Size",
    title: t("Common:Size"),
    enable: this.props.sizeColumnIsEnabled,
    resizable: true,
    sortBy: "Size",
    onClick: this.onFilter,
    onChange: this.onColumnChange,
  },
  {
    key: "Type",
    title: t("Common:Type"),
    enable: this.props.typeColumnIsEnabled,
    resizable: true,
    sortBy: "Type",
    onClick: this.onFilter,
    onChange: this.onColumnChange,
  },
  {
    key: "QuickButtons",
    title: "",
    enable: this.props.quickButtonsColumnIsEnabled,
    defaultSize: 75,
    resizable: false,
  },
];

export const roomsColumns = [
  {
    key: "Name",
    title: t("Common:Name"),
    resizable: true,
    enable: this.props.nameColumnIsEnabled,
    default: true,
    sortBy: "AZ",
    minWidth: 210,
    onClick: this.onFilter,
  },
  {
    key: "Author",
    title: t("ByAuthor"),
    enable: this.props.authorColumnIsEnabled,
    resizable: true,
    sortBy: "Author",
    onClick: this.onFilter,
    onChange: this.onColumnChange,
  },
  {
    key: "Created",
    title: t("ByCreation"),
    enable: this.props.createdColumnIsEnabled,
    resizable: true,
    sortBy: "DateAndTimeCreation",
    onClick: this.onFilter,
    onChange: this.onColumnChange,
  },
  {
    key: "Modified",
    title: t("ByLastModified"),
    enable: this.props.modifiedColumnIsEnabled,
    resizable: true,
    sortBy: "DateAndTime",
    onClick: this.onFilter,
    onChange: this.onColumnChange,
  },
];

export const trashColumns = [
  {
    key: "Name",
    title: t("Common:Name"),
    resizable: true,
    enable: this.props.nameColumnIsEnabled,
    default: true,
    sortBy: "AZ",
    minWidth: 210,
    onClick: this.onFilter,
  },
  {
    key: "Author",
    title: t("ByAuthor"),
    enable: this.props.authorColumnIsEnabled,
    resizable: true,
    sortBy: "Author",
    onClick: this.onFilter,
    onChange: this.onColumnChange,
  },
  {
    key: "Created",
    title: t("ByCreation"),
    enable: this.props.createdColumnIsEnabled,
    resizable: true,
    sortBy: "DateAndTimeCreation",
    onClick: this.onFilter,
    onChange: this.onColumnChange,
  },
  {
    key: "Room",
    title: t("Common:Room"),
    enable: this.props.roomColumnIsEnabled,
    resizable: true,
    sortBy: "Room",
    onClick: this.onFilter,
    onChange: this.onColumnChange,
  },
  {
    key: "Erasure",
    title: t("ByErasure"),
    enable: this.props.erasureColumnIsEnabled,
    resizable: true,
    sortBy: "DateAndTimeAutoDelete",
    onClick: this.onFilter,
    onChange: this.onColumnChange,
  },
  {
    key: "Size",
    title: t("Common:Size"),
    enable: this.props.sizeColumnIsEnabled,
    resizable: true,
    sortBy: "Size",
    onClick: this.onFilter,
    onChange: this.onColumnChange,
  },
  {
    key: "Type",
    title: t("Common:Type"),
    enable: this.props.typeColumnIsEnabled,
    resizable: true,
    sortBy: "Type",
    onClick: this.onFilter,
    onChange: this.onColumnChange,
  },
  {
    key: "QuickButtons",
    title: "",
    enable: this.props.quickButtonsColumnIsEnabled,
    defaultSize: 75,
    resizable: false,
  },
];
