// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASC.Mail.Core.Dao.Entities
{
    [Table("mail_server_server_x_tenant")]
    public partial class MailServerServerXTenant
    {
        [Key]
        [Column("id_tenant", TypeName = "int(11)")]
        public int IdTenant { get; set; }
        [Key]
        [Column("id_server", TypeName = "int(11)")]
        public int IdServer { get; set; }
    }
}