// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ASC.Core.Common.EF;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASC.Mail.Core.Dao.Entities
{
    [Table("mail_tag_addresses")]
    public partial class MailTagAddresses : BaseEntity
    {
        [Key]
        [Column("id_tag", TypeName = "int(11) unsigned")]
        public uint IdTag { get; set; }
        [Key]
        [Column("address", TypeName = "varchar(255)")]
        public string Address { get; set; }
        [Key]
        [Column("tenant", TypeName = "int(11)")]
        public int Tenant { get; set; }

        public override object[] GetKeys()
        {
            return new object[] { IdTag, Address, Tenant };
        }
    }
}