// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASC.Mail.Core.Dao.Entities
{
    [Table("mail_pop_unordered_domain")]
    public partial class MailPopUnorderedDomain
    {
        [Key]
        [Column("server", TypeName = "varchar(255)")]
        public string Server { get; set; }
    }
}