// <auto-generated />
using ASC.Core.Common.EF.Teamlabsite.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASC.Migrations.MySql.SaaS.Migrations
{
    [DbContext(typeof(TeamlabSiteContext))]
    partial class TeamlabSiteContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ASC.Core.Common.EF.Teamlabsite.Model.DbCache", b =>
                {
                    b.Property<string>("TenantAlias")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tenant_alias")
                        .UseCollation("utf8_general_ci")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("TenantAlias")
                        .HasName("PRIMARY");

                    b.ToTable("tenants_cache", (string)null);

                    b
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("Relational:Collation", "utf8_general_ci");
                });
#pragma warning restore 612, 618
        }
    }
}
