global using System;
global using System.Collections;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Linq.Expressions;
global using System.Net;
global using System.Net.Http;
global using System.Net.Http.Headers;
global using System.Net.Mime;
global using System.Runtime.Serialization;
global using System.Security;
global using System.Security.Principal;
global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Web;
global using System.Xml;

global using AppLimit.CloudComputing.SharpBox;
global using AppLimit.CloudComputing.SharpBox.Exceptions;
global using AppLimit.CloudComputing.SharpBox.StorageProvider;
global using AppLimit.CloudComputing.SharpBox.StorageProvider.DropBox;

global using ASC.Api.Collections;
global using ASC.Api.Core;
global using ASC.Api.Documents;
global using ASC.Api.Utils;
global using ASC.Common;
global using ASC.Common.Caching;
global using ASC.Common.Logging;
global using ASC.Common.Security.Authentication;
global using ASC.Common.Security.Authorizing;
global using ASC.Common.Threading;
global using ASC.Common.Utils;
global using ASC.Common.Web;
global using ASC.Core;
global using ASC.Core.ChunkedUploader;
global using ASC.Core.Common;
global using ASC.Core.Common.Configuration;
global using ASC.Core.Common.EF;
global using ASC.Core.Common.EF.Context;
global using ASC.Core.Common.EF.Model;
global using ASC.Core.Common.Settings;
global using ASC.Core.Notify.Signalr;
global using ASC.Core.Tenants;
global using ASC.Core.Users;
global using ASC.Data.Storage;
global using ASC.ElasticSearch;
global using ASC.ElasticSearch.Core;
global using ASC.ElasticSearch.Service;
global using ASC.FederatedLogin;
global using ASC.FederatedLogin.Helpers;
global using ASC.FederatedLogin.LoginProviders;
global using ASC.FederatedLogin.Profile;
global using ASC.Files.Core;
global using ASC.Files.Core.Data;
global using ASC.Files.Core.EF;
global using ASC.Files.Core.Model;
global using ASC.Files.Core.Resources;
global using ASC.Files.Core.Security;
global using ASC.Files.Core.Services.NotifyService;
global using ASC.Files.Core.Thirdparty;
global using ASC.Files.Thirdparty;
global using ASC.Files.Thirdparty.Box;
global using ASC.Files.Thirdparty.Dropbox;
global using ASC.Files.Thirdparty.GoogleDrive;
global using ASC.Files.Thirdparty.OneDrive;
global using ASC.Files.Thirdparty.ProviderDao;
global using ASC.Files.Thirdparty.SharePoint;
global using ASC.Files.Thirdparty.Sharpbox;
global using ASC.MessagingSystem.Models;
global using ASC.MessagingSystem.Core;
global using ASC.Notify.Model;
global using ASC.Notify.Patterns;
global using ASC.Notify.Recipients;
global using ASC.Security.Cryptography;
global using ASC.Web.Api.Models;
global using ASC.Web.Core;
global using ASC.Web.Core.Files;
global using ASC.Web.Core.ModuleManagement.Common;
global using ASC.Web.Core.PublicResources;
global using ASC.Web.Core.Subscriptions;
global using ASC.Web.Core.Users;
global using ASC.Web.Core.Utility.Skins;
global using ASC.Web.Core.WhiteLabel;
global using ASC.Web.Files.Api;
global using ASC.Web.Files.Classes;
global using ASC.Web.Files.Configuration;
global using ASC.Web.Files.Core;
global using ASC.Web.Files.Core.Compress;
global using ASC.Web.Files.Core.Entries;
global using ASC.Web.Files.Core.Search;
global using ASC.Web.Files.Helpers;
global using ASC.Web.Files.HttpHandlers;
global using ASC.Web.Files.Services.DocumentService;
global using ASC.Web.Files.Services.FFmpegService;
global using ASC.Web.Files.Services.WCFService;
global using ASC.Web.Files.Services.WCFService.FileOperations;
global using ASC.Web.Files.ThirdPartyApp;
global using ASC.Web.Files.Utils;
global using ASC.Web.Studio.Core;
global using ASC.Web.Studio.Core.Notify;
global using ASC.Web.Studio.UserControls.Statistics;
global using ASC.Web.Studio.Utility;

global using Box.V2;
global using Box.V2.Auth;
global using Box.V2.Config;
global using Box.V2.Models;

global using DocuSign.eSign.Api;
global using DocuSign.eSign.Client;
global using DocuSign.eSign.Model;

global using Dropbox.Api;
global using Dropbox.Api.Files;

global using Google;
global using Google.Apis.Auth.OAuth2;
global using Google.Apis.Auth.OAuth2.Flows;
global using Google.Apis.Auth.OAuth2.Responses;
global using Google.Apis.Drive.v3;
global using Google.Apis.Services;

global using ICSharpCode.SharpZipLib.GZip;
global using ICSharpCode.SharpZipLib.Tar;
global using ICSharpCode.SharpZipLib.Zip;

global using JWT;

global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.AspNetCore.Mvc.ModelBinding;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Infrastructure;
global using Microsoft.EntityFrameworkCore.Metadata;
global using Microsoft.EntityFrameworkCore.Migrations;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using Microsoft.Extensions.Primitives;
global using Microsoft.Graph;
global using Microsoft.OneDrive.Sdk;
global using Microsoft.SharePoint.Client;

global using Nest;

global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;

global using static ASC.Files.Core.Data.AbstractDao;
global using static ASC.Web.Core.Files.DocumentService;
global using static ASC.Web.Files.Services.DocumentService.DocumentServiceTracker;
global using static ASC.Web.Files.Utils.FileTracker;

global using HttpException = ASC.Common.Web.HttpException;
global using SecurityContext = ASC.Core.SecurityContext;
global using Constants = ASC.Core.Users.Constants;
global using UserInfo = ASC.Core.Users.UserInfo;
global using FilesDbContext = ASC.Files.Core.EF.FilesDbContext;
global using MySqlFilesDbContext = ASC.Files.Core.EF.MySqlFilesDbContext;
global using PostgreSqlFilesDbContext = ASC.Files.Core.EF.PostgreSqlFilesDbContext;
global using FileShare = ASC.Files.Core.Security.FileShare;
global using Tag = ASC.Files.Core.Tag;
global using Thumbnail = ASC.Files.Core.Thumbnail;
global using FileType = ASC.Web.Core.Files.FileType;
global using Token = ASC.Web.Files.ThirdPartyApp.Token;
global using FileShareLink = ASC.Web.Files.Utils.FileShareLink;
global using ModelSnapshot = Microsoft.EntityFrameworkCore.Infrastructure.ModelSnapshot;
global using ContentType = System.Net.Mime.ContentType;
global using JsonSerializer = System.Text.Json.JsonSerializer;
global using JsonTokenType = System.Text.Json.JsonTokenType;
global using JsonConverter = System.Text.Json.Serialization.JsonConverter;
global using JsonConverterAttribute = System.Text.Json.Serialization.JsonConverterAttribute;
global using JsonIgnoreAttribute = System.Text.Json.Serialization.JsonIgnoreAttribute;
