//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Core.PublicResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuditResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuditResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Core.PublicResources.AuditResource", typeof(AuditResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string ActionCol {
            get {
                return ResourceManager.GetString("ActionCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can download the report for the data available during the selected storage period to view the detailed statistics. Please note, that the logging is currently enabled for the Documents, Projects, CRM and People modules, as well as for portal settings..
        /// </summary>
        internal static string AuditDownloadText {
            get {
                return ResourceManager.GetString("AuditDownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the latest activity is shown at this page. The data itself is stored during the period, which can be entered to the field below (measured in days, 180 maximum):.
        /// </summary>
        internal static string AuditLatestText {
            get {
                return ResourceManager.GetString("AuditLatestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the portal is actively used, all the user activity will be displayed here: document creation and editing, participation in projects, CRM and other modules, and various other information..
        /// </summary>
        internal static string AuditTrailEmptyScreenDscr {
            get {
                return ResourceManager.GetString("AuditTrailEmptyScreenDscr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to be displayed here.
        /// </summary>
        internal static string AuditTrailEmptyScreenHeader {
            get {
                return ResourceManager.GetString("AuditTrailEmptyScreenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Trail.
        /// </summary>
        internal static string AuditTrailNav {
            get {
                return ResourceManager.GetString("AuditTrailNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Users.
        /// </summary>
        internal static string AuditTrailOnlineUsers {
            get {
                return ResourceManager.GetString("AuditTrailOnlineUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DateCol {
            get {
                return ResourceManager.GetString("DateCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and open report.
        /// </summary>
        internal static string DownloadReportBtn {
            get {
                return ResourceManager.GetString("DownloadReportBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not specified.
        /// </summary>
        internal static string EmailNotSpecified {
            get {
                return ResourceManager.GetString("EmailNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while the report is being generated....
        /// </summary>
        internal static string GenerateText {
            get {
                return ResourceManager.GetString("GenerateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can download the report for the data available during the selected storage period to view the detailed statistics..
        /// </summary>
        internal static string LoginDownloadText {
            get {
                return ResourceManager.GetString("LoginDownloadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When the portal is actively used, all the user successful login activity as well as the unsuccessful login attempts will be displayed here..
        /// </summary>
        internal static string LoginHistoryEmptyScreenDscr {
            get {
                return ResourceManager.GetString("LoginHistoryEmptyScreenDscr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to be displayed here.
        /// </summary>
        internal static string LoginHistoryEmptyScreenHeader {
            get {
                return ResourceManager.GetString("LoginHistoryEmptyScreenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login History.
        /// </summary>
        internal static string LoginHistoryNav {
            get {
                return ResourceManager.GetString("LoginHistoryNav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login History.
        /// </summary>
        internal static string LoginHistoryTitle {
            get {
                return ResourceManager.GetString("LoginHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only the latest activity is shown at this page. The data itself is stored during the period, which can be entered to the field below (measured in days, 180 maximum):.
        /// </summary>
        internal static string LoginLatestText {
            get {
                return ResourceManager.GetString("LoginLatestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period of storage.
        /// </summary>
        internal static string StoragePeriod {
            get {
                return ResourceManager.GetString("StoragePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalAuditItems {
            get {
                return ResourceManager.GetString("TotalAuditItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string UserCol {
            get {
                return ResourceManager.GetString("UserCol", resourceCulture);
            }
        }
    }
}
