//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASC.Web.Core.PublicResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChatResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChatResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASC.Web.Core.PublicResources.ChatResource", typeof(ChatResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation to chat room.
        /// </summary>
        internal static string ChatRoomInvite {
            get {
                return ResourceManager.GetString("ChatRoomInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ClearText {
            get {
                return ResourceManager.GetString("ClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all mini-chat windows.
        /// </summary>
        internal static string CloseAllWindows {
            get {
                return ResourceManager.GetString("CloseAllWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close item .
        /// </summary>
        internal static string CloseItem {
            get {
                return ResourceManager.GetString("CloseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close window.
        /// </summary>
        internal static string CloseMessageWindowAltTitle {
            get {
                return ResourceManager.GetString("CloseMessageWindowAltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat rooms.
        /// </summary>
        internal static string ConferenceGroupName {
            get {
                return ResourceManager.GetString("ConferenceGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend mini-chat.
        /// </summary>
        internal static string ExtendChatAltTitle {
            get {
                return ResourceManager.GetString("ExtendChatAltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please switch to Talk..
        /// </summary>
        internal static string GoTalk {
            get {
                return ResourceManager.GetString("GoTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Ctrl+Enter to send messages.
        /// </summary>
        internal static string HintCtrlEnterSender {
            get {
                return ResourceManager.GetString("HintCtrlEnterSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable sounds.
        /// </summary>
        internal static string HintSounds {
            get {
                return ResourceManager.GetString("HintSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your message...
        /// </summary>
        internal static string InputNotificationMessage {
            get {
                return ResourceManager.GetString("InputNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailings.
        /// </summary>
        internal static string MailingsGroupName {
            get {
                return ResourceManager.GetString("MailingsGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize all mini-chat windows.
        /// </summary>
        internal static string MinimizeAllWindows {
            get {
                return ResourceManager.GetString("MinimizeAllWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize all windows when out of focus.
        /// </summary>
        internal static string MinimizeAllWindowsIfLoseFocus {
            get {
                return ResourceManager.GetString("MinimizeAllWindowsIfLoseFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize window.
        /// </summary>
        internal static string MinimizeMessageWindowAltTitle {
            get {
                return ResourceManager.GetString("MinimizeMessageWindowAltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New message.
        /// </summary>
        internal static string NewMessageLabel {
            get {
                return ResourceManager.GetString("NewMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all mini-chat windows.
        /// </summary>
        internal static string RestoreAllWindows {
            get {
                return ResourceManager.GetString("RestoreAllWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand window.
        /// </summary>
        internal static string RestoreMessageWindowAltTitle {
            get {
                return ResourceManager.GetString("RestoreMessageWindowAltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server internal error..
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide mini-chat.
        /// </summary>
        internal static string ShowHideChatAltTitle {
            get {
                return ResourceManager.GetString("ShowHideChatAltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show invisible dialog windows.
        /// </summary>
        internal static string ShowInvisibleWindows {
            get {
                return ResourceManager.GetString("ShowInvisibleWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string SmallChatOptionsAltTitle {
            get {
                return ResourceManager.GetString("SmallChatOptionsAltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smileys.
        /// </summary>
        internal static string SmileysAltTitle {
            get {
                return ResourceManager.GetString("SmileysAltTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Away.
        /// </summary>
        internal static string StatusAway {
            get {
                return ResourceManager.GetString("StatusAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        internal static string StatusNA {
            get {
                return ResourceManager.GetString("StatusNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string StatusOffline {
            get {
                return ResourceManager.GetString("StatusOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string StatusOnline {
            get {
                return ResourceManager.GetString("StatusOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create chat room.
        /// </summary>
        internal static string TitleCreateRoom {
            get {
                return ResourceManager.GetString("TitleCreateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to typing the message....
        /// </summary>
        internal static string TypingMessage {
            get {
                return ResourceManager.GetString("TypingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contacts matching your search criteria can be found in list.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
