using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ASC.Core.Common.Migrations.MySql.FilesDbContextMySql
{
    public partial class FilesDbContextMySql : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.CreateTable(
                name: "files_converts",
                columns: table => new
                {
                    input = table.Column<string>(type: "varchar(50)", nullable: false, collation: "utf8_general_ci")
                        .Annotation("MySql:CharSet", "utf8"),
                    output = table.Column<string>(type: "varchar(50)", nullable: false, collation: "utf8_general_ci")
                        .Annotation("MySql:CharSet", "utf8")
                },
                constraints: table =>
                {
                    table.PrimaryKey("PRIMARY", x => new { x.input, x.output });
                })
                .Annotation("MySql:CharSet", "utf8mb4");

            migrationBuilder.InsertData(
                table: "files_converts",
                columns: new[] { "input", "output" },
                values: new object[,]
                {
                    { ".csv", ".ods" },
                    { ".csv", ".pdf" },
                    { ".csv", ".xlsx" },
                    { ".doc", ".docx" },
                    { ".doc", ".odt" },
                    { ".doc", ".pdf" },
                    { ".doc", ".rtf" },
                    { ".doc", ".txt" },
                    { ".docm", ".docx" },
                    { ".docm", ".odt" },
                    { ".docm", ".pdf" },
                    { ".docm", ".rtf" },
                    { ".docm", ".txt" },
                    { ".doct", ".docx" },
                    { ".docx", ".docxf" },
                    { ".docx", ".odt" },
                    { ".docx", ".pdf" },
                    { ".docx", ".rtf" },
                    { ".docx", ".txt" },
                    { ".docxf", ".docx" },
                    { ".docxf", ".dotx" },
                    { ".docxf", ".epub" },
                    { ".docxf", ".fb2" },
                    { ".docxf", ".html" },
                    { ".docxf", ".odt" },
                    { ".docxf", ".oform" },
                    { ".docxf", ".ott" },
                    { ".docxf", ".pdf" },
                    { ".docxf", ".rtf" },
                    { ".docxf", ".txt" },
                    { ".dot", ".docx" },
                    { ".dot", ".odt" },
                    { ".dot", ".pdf" },
                    { ".dot", ".rtf" },
                    { ".dot", ".txt" },
                    { ".dotm", ".docx" },
                    { ".dotm", ".odt" },
                    { ".dotm", ".pdf" },
                    { ".dotm", ".rtf" },
                    { ".dotm", ".txt" },
                    { ".dotx", ".docx" },
                    { ".dotx", ".odt" },
                    { ".dotx", ".pdf" },
                    { ".dotx", ".rtf" },
                    { ".dotx", ".txt" },
                    { ".epub", ".docx" },
                    { ".epub", ".odt" },
                    { ".epub", ".pdf" },
                    { ".epub", ".rtf" },
                    { ".epub", ".txt" },
                    { ".fb2", ".docx" },
                    { ".fb2", ".odt" },
                    { ".fb2", ".pdf" },
                    { ".fb2", ".rtf" },
                    { ".fb2", ".txt" },
                    { ".fodp", ".odp" },
                    { ".fodp", ".pdf" },
                    { ".fodp", ".pptx" },
                    { ".fods", ".csv" },
                    { ".fods", ".ods" },
                    { ".fods", ".pdf" },
                    { ".fods", ".xlsx" },
                    { ".fodt", ".docx" },
                    { ".fodt", ".odt" },
                    { ".fodt", ".pdf" },
                    { ".fodt", ".rtf" },
                    { ".fodt", ".txt" },
                    { ".html", ".docx" },
                    { ".html", ".odt" },
                    { ".html", ".pdf" },
                    { ".html", ".rtf" },
                    { ".html", ".txt" },
                    { ".mht", ".docx" },
                    { ".mht", ".odt" },
                    { ".mht", ".pdf" },
                    { ".mht", ".rtf" },
                    { ".mht", ".txt" },
                    { ".odp", ".pdf" },
                    { ".odp", ".pptx" },
                    { ".ods", ".csv" },
                    { ".ods", ".pdf" },
                    { ".ods", ".xlsx" },
                    { ".odt", ".docx" },
                    { ".odt", ".pdf" },
                    { ".odt", ".rtf" },
                    { ".odt", ".txt" },
                    { ".otp", ".odp" },
                    { ".otp", ".pdf" },
                    { ".otp", ".pptx" },
                    { ".ots", ".csv" },
                    { ".ots", ".ods" },
                    { ".ots", ".pdf" },
                    { ".ots", ".xlsx" },
                    { ".ott", ".docx" },
                    { ".ott", ".odt" },
                    { ".ott", ".pdf" },
                    { ".ott", ".rtf" },
                    { ".ott", ".txt" },
                    { ".pot", ".odp" },
                    { ".pot", ".pdf" },
                    { ".pot", ".pptx" },
                    { ".potm", ".odp" },
                    { ".potm", ".pdf" },
                    { ".potm", ".pptx" },
                    { ".potx", ".odp" },
                    { ".potx", ".pdf" },
                    { ".potx", ".pptx" },
                    { ".pps", ".odp" },
                    { ".pps", ".pdf" },
                    { ".pps", ".pptx" },
                    { ".ppsm", ".odp" },
                    { ".ppsm", ".pdf" },
                    { ".ppsm", ".pptx" },
                    { ".ppsx", ".odp" },
                    { ".ppsx", ".pdf" },
                    { ".ppsx", ".pptx" },
                    { ".ppt", ".odp" },
                    { ".ppt", ".pdf" },
                    { ".ppt", ".pptx" },
                    { ".pptm", ".odp" },
                    { ".pptm", ".pdf" },
                    { ".pptm", ".pptx" },
                    { ".pptt", ".odp" },
                    { ".pptt", ".pdf" },
                    { ".pptt", ".pptx" },
                    { ".pptx", ".odp" },
                    { ".pptx", ".pdf" },
                    { ".rtf", ".docx" },
                    { ".rtf", ".odp" },
                    { ".rtf", ".pdf" },
                    { ".rtf", ".txt" },
                    { ".txt", ".docx" },
                    { ".txt", ".odp" },
                    { ".txt", ".pdf" },
                    { ".txt", ".rtx" },
                    { ".xls", ".csv" },
                    { ".xls", ".ods" },
                    { ".xls", ".pdf" },
                    { ".xls", ".xlsx" },
                    { ".xlsm", ".csv" },
                    { ".xlsm", ".ods" },
                    { ".xlsm", ".pdf" },
                    { ".xlsm", ".xlsx" },
                    { ".xlst", ".csv" },
                    { ".xlst", ".ods" },
                    { ".xlst", ".pdf" },
                    { ".xlst", ".xlsx" },
                    { ".xlt", ".csv" },
                    { ".xlt", ".ods" },
                    { ".xlt", ".pdf" },
                    { ".xlt", ".xlsx" },
                    { ".xltm", ".csv" },
                    { ".xltm", ".ods" },
                    { ".xltm", ".pdf" },
                    { ".xltm", ".xlsx" },
                    { ".xltx", ".csv" },
                    { ".xltx", ".ods" },
                    { ".xltx", ".pdf" },
                    { ".xltx", ".xlsx" },
                    { ".xps", ".pdf" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "files_converts");
        }
    }
}
