export const ThemeType = {
  Button: "button",
  MainButton: "mainButton",
  CatalogItem: "catalogItem",
  Badge: "badge",
  SubmenuText: "submenuText",
  SubmenuItemLabel: "submenuItemLabel",
  ToggleButton: "toggleButton",
  TabContainer: "tabContainer",
  IconButton: "iconButton",
  MainButtonMobile: "mainButtonMobile",
  IndicatorFilterButton: "indicatorFilterButton",
  FilterBlockItemTag: "filterBlockItemTag",
  IconWrapper: "iconWrapper",
  Calendar: "calendar",
  VersionBadge: "versionBadge",
  Textarea: "textarea",
  InputBlock: "inputBlock",
  TextInput: "textInput",
  ComboButton: "comboButton",
};
