export const ThemeType = {
  Button: "button",
  MainButton: "mainButton",
  CatalogItem: "catalogItem",
  Badge: "badge",
  SubmenuText: "submenuText",
  SubmenuItemLabel: "submenuItemLabel",
  ToggleButton: "toggleButton",
  TabContainer: "tabContainer",
  IconButton: "iconButton",
  MainButtonMobile: "mainButtonMobile",
  IndicatorFilterButton: "indicatorFilterButtonTheme",
  FilterBlockItemTag: "filterBlockItemTagTheme",
  IconWrapper: "iconWrapperTheme",
  Calendar: "calendarTheme",
};
