// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASC.Mail.Core.Dao.Entities
{
    [Table("crm_contact_info")]
    public partial class CrmContactInfo
    {
        [Key]
        [Column("id", TypeName = "int(10)")]
        public int Id { get; set; }
        [Required]
        [Column("data", TypeName = "text")]
        public string Data { get; set; }
        [Column("category", TypeName = "int(255)")]
        public int Category { get; set; }
        [Column("tenant_id", TypeName = "int(255)")]
        public int TenantId { get; set; }
        [Column("is_primary", TypeName = "tinyint(4)")]
        public sbyte IsPrimary { get; set; }
        [Column("contact_id", TypeName = "int(11)")]
        public int ContactId { get; set; }
        [Column("type", TypeName = "int(255)")]
        public int Type { get; set; }
        [Column("last_modifed_on", TypeName = "datetime")]
        public DateTime? LastModifedOn { get; set; }
        [Column("last_modifed_by", TypeName = "char(38)")]
        public string LastModifedBy { get; set; }
    }
    public static class CrmContactInfoExtension
    {
        public static ModelBuilder AddCrmContactInfo(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CrmContactInfo>(entity =>
            {
                entity.HasIndex(e => e.LastModifedOn)
                    .HasDatabaseName("last_modifed_on");

                entity.HasIndex(e => new { e.TenantId, e.ContactId })
                    .HasDatabaseName("IX_Contact");

                entity.Property(e => e.Data)
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");

                entity.Property(e => e.LastModifedBy)
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");
            });

            return modelBuilder;
        }
    }
}