// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASC.Mail.Core.Dao.Entities
{
    [Table("crm_entity_tag")]
    public partial class CrmEntityTag
    {
        [Key]
        [Column("tag_id", TypeName = "int(11)")]
        public int TagId { get; set; }
        [Required]
        [Column("entity_id", TypeName = "int(11)")]
        public int EntityId { get; set; }
        [Required]
        [Column("entity_type", TypeName = "int(11)")]
        public int EntityType { get; set; }
    }

    public static class CrmEntityTagExtension
    {
        public static ModelBuilder AddCrmEntityTag(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CrmEntityTag>(entity =>
            {
                entity.HasIndex(e => new { e.TagId, e.EntityId, e.EntityType })
                    .HasDatabaseName("PRIMARY");

                entity.Property(e => e.TagId)
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");

                entity.Property(e => e.EntityId)
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");

                entity.Property(e => e.EntityType)
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");
            });

            return modelBuilder;
        }
    }
}