// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASC.Mail.Core.Dao.Entities
{
    [Table("mail_display_images")]
    public partial class MailDisplayImages
    {
        [Key]
        [Column("tenant", TypeName = "int(10)")]
        public int Tenant { get; set; }
        [Key]
        [Column("id_user", TypeName = "varchar(255)")]
        public string IdUser { get; set; }
        [Key]
        [Column("address", TypeName = "varchar(255)")]
        public string Address { get; set; }
    }

    public static class MailDisplayImagesExtension
    {
        public static ModelBuilder AddMailDisplayImages(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MailDisplayImages>(entity =>
            {
                entity.HasKey(e => new { e.Tenant, e.IdUser, e.Address })
                    .HasName("PRIMARY");

                entity.Property(e => e.IdUser)
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");

                entity.Property(e => e.Address)
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");
            });

            return modelBuilder;
        }
    }
}