// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASC.Mail.Core.Dao.Entities
{
    [Table("mail_pop_unordered_domain")]
    public partial class MailPopUnorderedDomain
    {
        [Key]
        [Column("server", TypeName = "varchar(255)")]
        public string Server { get; set; }
    }

    public static class MailPopUnorderedDomainExtension
    {
        public static ModelBuilder AddMailPopUnorderedDomain(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MailPopUnorderedDomain>(entity =>
            {
                entity.HasKey(e => e.Server)
                    .HasName("PRIMARY");

                entity.Property(e => e.Server)
                    .HasCharSet("utf8")
                    .UseCollation("utf8_general_ci");
            });

            return modelBuilder;
        }
    }
}