// <auto-generated />
using System;
using ASC.Core.Common.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ASC.Core.Common.Migrations.Npgsql.AccountLinkContextNpgsql
{
    [DbContext(typeof(PostgreSqlAccountLinkContext))]
    [Migration("20200928233349_AccountLinkContextNpgsql")]
    partial class AccountLinkContextNpgsql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ASC.Core.Common.EF.Model.AccountLinks", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<string>("UId")
                        .HasColumnName("uid")
                        .HasColumnType("character varying(200)")
                        .HasMaxLength(200);

                    b.Property<DateTime>("Linked")
                        .HasColumnName("linked")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnName("profile")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("provider")
                        .HasColumnType("character(60)")
                        .HasDefaultValueSql("NULL")
                        .IsFixedLength(true)
                        .HasMaxLength(60);

                    b.HasKey("Id", "UId")
                        .HasName("account_links_pkey");

                    b.HasIndex("UId")
                        .HasName("uid");

                    b.ToTable("account_links","onlyoffice");
                });
#pragma warning restore 612, 618
        }
    }
}
