// <auto-generated />
using ASC.Core.Common.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace ASC.Core.Common.Migrations.MySql.TelegramDbContextMySql
{
    [DbContext(typeof(MySqlTelegramDbContext))]
    partial class TelegramDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ASC.Core.Common.EF.Model.TelegramUser", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnName("tenant_id")
                        .HasColumnType("int");

                    b.Property<string>("PortalUserId")
                        .HasColumnName("portal_user_id")
                        .HasColumnType("varchar(38)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<int>("TelegramUserId")
                        .HasColumnName("telegram_user_id")
                        .HasColumnType("int");

                    b.HasKey("TenantId", "PortalUserId")
                        .HasName("PRIMARY");

                    b.HasIndex("TelegramUserId")
                        .HasName("tgId");

                    b.ToTable("telegram_users");
                });
#pragma warning restore 612, 618
        }
    }
}
