// <auto-generated />
using System;
using ASC.Core.Common.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace ASC.Core.Common.Migrations.MySql.VoipDbContextMySql
{
    [DbContext(typeof(MySqlVoipDbContext))]
    partial class VoipDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ASC.Core.Common.EF.Model.CrmContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnName("company_id")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnName("company_name")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<int>("ContactTypeId")
                        .HasColumnName("contact_type_id")
                        .HasColumnType("int");

                    b.Property<string>("CreateBy")
                        .IsRequired()
                        .HasColumnName("create_by")
                        .HasColumnType("char(38)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<DateTime>("CreateOn")
                        .HasColumnName("create_on")
                        .HasColumnType("datetime");

                    b.Property<string>("Currency")
                        .HasColumnName("currency")
                        .HasColumnType("varchar(3)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("DisplayName")
                        .HasColumnName("display_name")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("FirstName")
                        .HasColumnName("first_name")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("Industry")
                        .HasColumnName("industry")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<bool>("IsCompany")
                        .HasColumnName("is_company")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsShared")
                        .HasColumnName("is_shared")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastModifedBy")
                        .IsRequired()
                        .HasColumnName("last_modifed_by")
                        .HasColumnType("char(38)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<DateTime>("LastModifedOn")
                        .HasColumnName("last_modifed_on")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .HasColumnName("last_name")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("Notes")
                        .HasColumnName("notes")
                        .HasColumnType("text")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<int>("StatusId")
                        .HasColumnName("status_id")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnName("tenant_id")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnName("title")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.HasKey("Id");

                    b.HasIndex("CreateOn")
                        .HasName("create_on");

                    b.HasIndex("LastModifedOn", "TenantId")
                        .HasName("last_modifed_on");

                    b.HasIndex("TenantId", "CompanyId")
                        .HasName("company_id");

                    b.HasIndex("TenantId", "DisplayName")
                        .HasName("display_name");

                    b.ToTable("crm_contact");
                });

            modelBuilder.Entity("ASC.Core.Common.EF.Model.DbVoipCall", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("AnsweredBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("answered_by")
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("'00000000-0000-0000-0000-000000000000'")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<int>("ContactId")
                        .HasColumnName("contact_id")
                        .HasColumnType("int");

                    b.Property<int?>("CrmContactId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DialDate")
                        .HasColumnName("dial_date")
                        .HasColumnType("datetime");

                    b.Property<int>("DialDuration")
                        .HasColumnName("dial_duration")
                        .HasColumnType("int");

                    b.Property<string>("NumberFrom")
                        .IsRequired()
                        .HasColumnName("number_from")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("NumberTo")
                        .IsRequired()
                        .HasColumnName("number_to")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("ParentCallId")
                        .IsRequired()
                        .HasColumnName("parent_call_id")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("RecordDuration")
                        .HasColumnName("record_duration")
                        .HasColumnType("int");

                    b.Property<decimal>("RecordPrice")
                        .HasColumnName("record_price")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("RecordSid")
                        .HasColumnName("record_sid")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("RecordUrl")
                        .HasColumnName("record_url")
                        .HasColumnType("text")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<int>("Status")
                        .HasColumnName("status")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnName("tenant_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CrmContactId");

                    b.HasIndex("TenantId")
                        .HasName("tenant_id");

                    b.HasIndex("ParentCallId", "TenantId")
                        .HasName("parent_call_id");

                    b.ToTable("crm_voip_calls");
                });

            modelBuilder.Entity("ASC.Core.Common.EF.Model.VoipNumber", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnName("id")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("Alias")
                        .HasColumnName("alias")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnName("number")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<string>("Settings")
                        .HasColumnName("settings")
                        .HasColumnType("text")
                        .HasAnnotation("MySql:CharSet", "utf8")
                        .HasAnnotation("MySql:Collation", "utf8_general_ci");

                    b.Property<int>("TenantId")
                        .HasColumnName("tenant_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasName("tenant_id");

                    b.ToTable("crm_voip_number");
                });

            modelBuilder.Entity("ASC.Core.Common.EF.Model.DbVoipCall", b =>
                {
                    b.HasOne("ASC.Core.Common.EF.Model.CrmContact", "CrmContact")
                        .WithMany()
                        .HasForeignKey("CrmContactId");
                });
#pragma warning restore 612, 618
        }
    }
}
