// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ASC.CRM.Core.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASC.CRM.Core.EF
{
    [Table("crm_field_description")]
    public partial class DbFieldDescription : IDbCrm
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        
        [Column("tenant_id", TypeName = "int(11)")]
        public int TenantId { get; set; }
        
        [Required]
        [Column("label", TypeName = "varchar(255)")]
        public string Label { get; set; }
        
        [Column("type", TypeName = "int(11)")]
        public CustomFieldType Type { get; set; }
        
        [Column("sort_order", TypeName = "int(11)")]
        public int SortOrder { get; set; }
        
        [Column("mask", TypeName = "text")]
        public string Mask { get; set; }

        [Column("entity_type", TypeName = "int(255)")]
        public EntityType EntityType { get; set; }
    }
}