// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ASC.CRM.Core.EF
{
    [Table("crm_invoice_item")]
    public partial class DbInvoiceItem : IDbCrm
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Required]
        [Column("title", TypeName = "varchar(255)")]
        public string Title { get; set; }
        [Required]
        [Column("description", TypeName = "text")]
        public string Description { get; set; }
        [Required]
        [Column("stock_keeping_unit", TypeName = "varchar(255)")]
        public string StockKeepingUnit { get; set; }
        [Column("price", TypeName = "decimal(10,2)")]
        public decimal Price { get; set; }
        [Column("stock_quantity", TypeName = "decimal(10,2)")]
        public decimal StockQuantity { get; set; }
        [Column("track_inventory", TypeName = "tinyint(4)")]
        public bool TrackInventory { get; set; }
        [Column("invoice_tax1_id", TypeName = "int(11)")]
        public int InvoiceTax1Id { get; set; }
        [Column("invoice_tax2_id", TypeName = "int(11)")]
        public int InvoiceTax2Id { get; set; }
        [Required]
        [Column("currency", TypeName = "varchar(255)")]
        public string Currency { get; set; }
        
        [Column("create_on", TypeName = "datetime")]
        public DateTime CreateOn { get; set; }

        [Required]
        [Column("create_by", TypeName = "char(38)")]
        public Guid CreateBy { get; set; }
        
        [Column("last_modifed_on", TypeName = "datetime")]
        public DateTime? LastModifedOn { get; set; }

        [Column("last_modifed_by", TypeName = "char(38)")]
        public Guid LastModifedBy { get; set; }
        [Column("tenant_id", TypeName = "int(11)")]
        public int TenantId { get; set; }
    }
}