// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using ASC.VoipService;

namespace ASC.CRM.Core.EF
{
    [Table("crm_voip_calls")]
    public partial class DbVoipCalls : IDbCrm
    {
        [Key]
        [Column("id", TypeName = "varchar(50)")]
        public string Id { get; set; }
        [Required]
        [Column("parent_call_id", TypeName = "varchar(50)")]
        public string ParentCallId { get; set; }
        [Required]
        [Column("number_from", TypeName = "varchar(50)")]
        public string NumberFrom { get; set; }
        [Required]
        [Column("number_to", TypeName = "varchar(50)")]
        public string NumberTo { get; set; }
        [Column("status", TypeName = "int(10)")]
        public VoipCallStatus Status { get; set; }
        [Required]
        [Column("answered_by", TypeName = "varchar(50)")]
        public Guid AnsweredBy { get; set; }
        [Column("dial_date", TypeName = "datetime")]
        public DateTime? DialDate { get; set; }
        [Column("dial_duration", TypeName = "int(11)")]
        public int? DialDuration { get; set; }
        [Column("record_sid", TypeName = "varchar(50)")]
        public string RecordSid { get; set; }
        [Column("record_url", TypeName = "text")]
        public string RecordUrl { get; set; }
        [Column("record_duration", TypeName = "int(11)")]
        public int? RecordDuration { get; set; }
        [Column("record_price", TypeName = "decimal(10,4)")]
        public decimal RecordPrice { get; set; }
        [Column("contact_id", TypeName = "int(10)")]
        public int? ContactId { get; set; }
        [Column("price", TypeName = "decimal(10,4)")]
        public decimal? Price { get; set; }
        [Column("tenant_id", TypeName = "int(10)")]
        public int TenantId { get; set; }
    }
}