name: 4testing multiarch-build

on:
  push:
    branches: 
      - 'feature/docker-build-profiles'
env:
    DOCKER_PATH: "./build/install/docker"
    REPO: "onlyoffice"
    DOCKER_IMAGE_PREFIX: "4testing-docspace"
    DOCKERFILE: "{DOCKER_PATH}/Dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build 4testing
        run: |
          DOCKER_TAG=dev-profile

          docker buildx bake -f ${DOCKER_PATH}/build.yml \
          --set *.platform=linux/amd64 \
          --push
        shell: bash
