name: 4testing multiarch-build

on:
  schedule:
    - cron: '0 20 * * *' 
env:
  DOCKER_PATH: "/buildtools/install/docker"
  REPO: "onlyoffice"
  DOCKER_IMAGE_PREFIX: "4testing-docspace"
  DOCKERFILE: "Dockerfile.app"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64]
    steps:
      - name: Find Latest Release Branch
        id: release-branch-finder
        uses: jsryudev/release-branch-finder@v0.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-branch-prefix: 'develop'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.release-branch-finder.outputs.release-branch }}
          submodules: 'recursive'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/local/lib/android /opt/ghc
          sudo docker image prune --all --force

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build 4testing
        run: |
          cd .${DOCKER_PATH}
          GITHUB_REF_NAME=${{ steps.release-branch-finder.outputs.release-branch }}
          DOCKER_TAG=2.0.0.${{github.run_number}}
          export DOCKER_TAG

          docker buildx bake -f build.yml \
          --set *.args.GIT_BRANCH=$GITHUB_REF_NAME \
          --set *.platform=linux/amd64 \
          --push
        shell: bash
