name: night-build

on:
  schedule:
    - cron: '*/30 * * * *'

env:
    DOCKER_PATH: "/build/install/docker"
    REPO: "lemmav"
    DOCKER_IMAGE_PREFIX: "4testing-docspace"
    DOCKERFILE: "Dockerfile.app"
    FILE: "build.yml"
    STATUS: ""
    


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64]
    steps:
      - name: Find Latest Release Branch
        id: release-branch-finder
        uses: jsryudev/release-branch-finder@v0.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-branch-prefix: release
     
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.release-branch-finder.outputs.release-branch }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build 4testing
      
        run: |
          cd .${DOCKER_PATH}
          GITHUB_REF_NAME=${{ steps.release-branch-finder.outputs.release-branch }}
          TAG=${{github.run_number}}
          export DOCKER_TAG=$(echo "${GITHUB_REF_NAME}" | sed '/^release\b\|^hotfix\b\|^feature\b/s/release.*\/\|hotfix.*\/\|feature.*\///')

          docker buildx bake -f build.yml \
          --set *.args.GIT_BRANCH=$GITHUB_REF_NAME \
          --set *.platform=linux/amd64 \
          --push

        shell: bash
      
