name: Release RPM DEB

on:
  push:
    # paths:
    # - build/install/deb**
    # - build/install/rpm**
  workflow_dispatch:
  
env:
  BRANCH_NAME: $(echo ${GITHUB_REF#refs/heads/})
  PRODUCT: $(echo "${{ github.event.repository.name }}" |  tr '[:upper:]' '[:lower:]' )
  BUILD_NUMBER: "${{ github.run_number }}"


jobs:
  build_deb:
    name: Build .deb package
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Generate GPG key
        run: |
          export DEBEMAIL=mymail@example.com
          export DEBFULLNAME="Elbakyan Shirak"
          cat << EOF >> gen-key-instruction
          Key-Type: RSA
          Key-Length: 4096
          Name-Real: Elbakyan-Shirak
          Name-Email: el.shirak@internet.com"
          Expire-Date: 0
          Passphrase: 42*Hello_I-love-you!1337
          %commit
          %echo Done
          EOF
          gpg --batch --gen-key gen-key-instruction
          gpg --list-keys
          ls -la ~/.gnupg/private-keys-v1.d/
          ls -la ~/.gnupg
          gpg --export --armor --output public.key el.shirak@internet.com
          cat public.key
          gpg --import public.key
          # gpg --import ~/.gnupg/private-keys-v1.d/*.key
          
          
      - name: Get files from repository
        uses: actions/checkout@v2
              
      - name: INSTALL tools & Prepare build /home/runner/work/DocSpace/DocSpace
        id: get_vars
        run: |
          wget -O - https://dl.yarnpkg.com/debian/pubkey.gpg | sudo gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/yarnkey.gpg --import
          sudo chmod 644 /usr/share/keyrings/yarnkey.gpg
          echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          wget https://packages.microsoft.com/config/$(lsb_release -is | tr [:upper:] [:lower:])/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          wget -O - https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt install -y dotnet-sdk-7.0 yarn nodejs dh-make
          sudo apt-get install dpkg-sig
          sudo npm install -g json
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
          echo "VERSION=$(echo "${{ github.ref }}" | grep  -oP '\d+\.\d+\.\d+' || echo "1.0.0")" >> $GITHUB_OUTPUT
          
      - name: BUILD package DEB
        shell: bash
        run: |
          cd build/install/deb/ 
          find ../ -type f -exec sed -i "s/{{product}}/${{ env.PRODUCT }}/g" {} ';'
          sed -i "s/{{package_header_tag_version}}/$(echo ${{ github.ref }} | grep -oP '\d+\.\d+\.\d+' || echo "1.0.0" ).$BUILD_NUMBER/g" debian/changelog debian/control
          dpkg-buildpackage -us -uc
      
      - name: Sign packages and check 
        run: |
          export GPG_TTY=$(tty)
          keyID="$(gpg --list-keys --keyid-format short | awk '/^pub/ {print $2}' | cut -d'/' -f2)"
          echo "keyID"
          
          dpkg-sig -k "$keyID" --sign builder /home/runner/work/DocSpace/DocSpace/build/install/*.deb

        
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          commit: "${{ steps.get_vars.outputs.BRANCH_NAME }}"
          tag: "${{ steps.get_vars.outputs.VERSION }}-${{ env.BUILD_NUMBER }}"
          name: DocSpace packeges release ${{ env.BUILD_NUMBER }}
          body: Here you may find packages for DocSpace
          artifacts: /home/runner/work/DocSpace/DocSpace/build/install/*.deb
          
          
  build_rpm:
    name: Build .rpm package
    runs-on: ubuntu-latest
    permissions:
      contents: write
 
    steps:
      - name: Import GPG 
        uses: crazy-max/ghaction-import-gpg@v5
        with: 
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Get files from repository.
        uses: actions/checkout@v2

      - name: INSTALL tools & Prepare build
        id: get_vars
        run: |
          wget -O - https://dl.yarnpkg.com/debian/pubkey.gpg | sudo gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/yarnkey.gpg --import
          sudo chmod 644 /usr/share/keyrings/yarnkey.gpg
          echo "deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          wget https://packages.microsoft.com/config/$(lsb_release -is | tr [:upper:] [:lower:])/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          wget -O - https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt install -y dotnet-sdk-7.0 yarn nodejs dh-make rename
          sudo npm install -g json
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
          echo "VERSION=$(echo "${ GITHUB_REF##*/ }" | grep  -oP '\d+\.\d+\.\d+' || echo "1.0.0")" >> $GITHUB_OUTPUT
          
      - name: BUILD package RPM
        run: |
          cd build/install/rpm/SPECS
          mv ./SOURCES/product.rpmlintrc ./SOURCES/${{ env.PRODUCT }}.rpmlintrc
          wget https://github.com/elshirak/${{ env.PRODUCT }}/archive/${{ env.BRANCH_NAME }}.tar.gz -O ./SOURCES/DocSpace-$(echo ${{ env.BRANCH_NAME }} | tr '/' '-').tar.gz 
          wget https://github.com/ONLYOFFICE/document-templates/archive/main/community-server.tar.gz -O ./SOURCES/document-templates-main-community-server.tar.gz
          wget https://github.com/ONLYOFFICE/dictionaries/archive/master.tar.gz -O ./SOURCES/dictionaries-master.tar.gz
          sed -i -e '/BuildRequires/d' product.spec
          rpmbuild -D "_signature gpg" -D "GIT_BRANCH $(echo ${{ env.BRANCH_NAME }} | tr '/' '-')" -D "_topdir $(pwd)" -D "version ${{ steps.get_vars.outputs.VERSION }}" -D "release ${{ env.BUILD_NUMBER }}" -ba product.spec


      - name: Sign packages and check 
        run: |
          cp /home/runner/work/DocSpace/DocSpace/build/install/rpm/SPECS/RPMS/x86_64/*.rpm ~ 
          ls -la ~
          echo "//////////////////////////////////////"
          
          ls -la /home/runner/work/DocSpace/DocSpace/build/install/rpm/SPECS/RPMS/x86_64/
          pwd
          
          sudo chmod -R 777 /home/runner/work/DocSpace/DocSpace/build/install/rpm/SPECS/RPMS
          sudo chown -R $USER /home/runner/work/DocSpace/DocSpace/build/install/rpm/SPECS/RPMS/
          sudo chgrp -R $USER /home/runner/work/DocSpace/DocSpace/build/install/rpm/SPECS/RPMS/
          
          ls -la /home/runner/work/DocSpace/DocSpace/build/install/rpm/SPECS/RPMS/x86_64/
          echo "........................................"
          
          ls -la /home/runner/work/DocSpace/DocSpace/build/install/rpm/SPECS/RPMS/
          echo "........................................"
          
          ls -la /home/runner/work/DocSpace/DocSpace/build/install/rpm/SPECS
          echo "........................................"
          
          ls -la /home/runner/work/DocSpace/DocSpace/build/install/rpm
          echo "........................................"
          
          export GPG_TTY=$(tty)
          rpm --checksig /home/runner/*.rpm
          rpmsign --define "_gpg_name Ascensio System SIA" --addsign /home/runner/*.rpm
          rpm --checksig /home/runner/*.rpm

          
      
      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          commit: "${{ steps.get_vars.outputs.BRANCH_NAME }}"
          tag: "${{ steps.get_vars.outputs.VERSION }}-${{ env.BUILD_NUMBER }}"
          name: DocSpace packeges release ${{ env.BUILD_NUMBER }}
          body: Here you may find packages for DocSpace
          artifacts: /home/runner/work/DocSpace/DocSpace/build/install/rpm/SPECS/RPMS/x86_64/*.rpm
